### ISSUE TITLE
Compatibility with Idea 2021.1

### ISSUE THREAD

**Issue by materemias** [TheBlob42/idea-which-key#7]
the plugin throws an exception on start:

```
com.intellij.diagnostic.PluginException: ID "VimShortcutKeyAction" is already taken by action "Shortcuts ()" (Plugin: IdeaVim). Action " (null)" (Plugin: IDEA Which-Key) cannot use the same ID [Plugin: eu.theblob42.idea.whichkey]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:389)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:384)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerChameleon(ActionManagerImpl.java:1308)
...
```

**Comment by TheBlob42** [comment]
Please check the section about [known issues](https://github.com/TheBlob42/idea-which-key#known-issues) in the README for a detailed explanation :slightly_smiling_face: 

This should not affect the usage of the plugin in any way. But since version 2021.1 they show these "startup errors" more prominent, but it is not a new issue. If you have more questions, don't hesitate to ask :+1:

**Comment by materemias** [comment]
sure thanks for the explanation!
